variable "project_name" {}
variable "region" {}
variable "function_entry_point" {}
variable "function_name" {}
variable "function_description" {}
variable "function_filename" {}
variable "function_path" {}
variable "oauth2_client_secret" {}
variable "oauth2_client_id" {}
variable "oauth2_token_issuer" {}
variable "jwks_uri" {}
